Repository Business-Bridge/businessbridge-front-end, pull requests merged in 2023-12, with the labels that each got.

#29 Feat/#3/approval list view
  .idea/.gitignore
  .idea/businessbridge-front-end.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  business-bridge-react/package-lock.json
  business-bridge-react/package.json
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/ApprovalAPICalls.js
  business-bridge-react/src/components/approval/form/BusinessDraftForm.js
  business-bridge-react/src/components/approval/item/ApprovalButton.js
  business-bridge-react/src/components/approval/item/Approver.js
  business-bridge-react/src/components/approval/item/BusinessDraftItem.js
  business-bridge-react/src/components/approval/main/InProgressListItem.js
  business-bridge-react/src/components/approval/main/InProgressLists.js
  business-bridge-react/src/components/common/Header.js
  business-bridge-react/src/components/common/Menu.js
  business-bridge-react/src/components/nav/ApprovalNavbar.js
  business-bridge-react/src/css/Sales.css
  business-bridge-react/src/css/approval.css
  business-bridge-react/src/css/stylee.css
  business-bridge-react/src/layouts/ApprovalLayout.js
  business-bridge-react/src/layouts/Layout.js
  business-bridge-react/src/modules/ApprovalModule.js
  business-bridge-react/src/modules/index.js
  business-bridge-react/src/pages/approval/AppDetail.js
  business-bridge-react/src/pages/approval/AppMain.js
  business-bridge-react/src/pages/approval/AppWrite.js
  business-bridge-react/src/pages/approval/DraftApps.js
  business-bridge-react/src/pages/approval/DraftAppsByStatus.js
  business-bridge-react/src/pages/approval/ReceiveApps.js
  business-bridge-react/src/pages/approval/ReceiveAppsByStatus.js
  business-bridge-react/src/pages/approval/UpcomingApps.js
  business-bridge-react/src/router/ProtectedRoute.js
  business-bridge-react/src/utils/TokenUtils.js
Labels: 🖥frontend, 🎇feature

#31 Feat#7 sales first
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/SalesAPICalls.js
  business-bridge-react/src/components/common/SalesNavbar.js
  business-bridge-react/src/components/modal/SalesRegistModal.js
  business-bridge-react/src/css/Sales.css
  business-bridge-react/src/layouts/SalesLayout.js
  business-bridge-react/src/modules/SalesModule.js
  business-bridge-react/src/pages/businessbridge/sales/admin/SalesModify.js
  business-bridge-react/src/pages/businessbridge/sales/admin/SalesRegist.js
  business-bridge-react/src/pages/sales/SalesDetail.js
  business-bridge-react/src/pages/sales/SalesList.js
Labels: 👩‍💻backend, 🖥frontend

#33 Feat/#4/approval detail
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/ApprovalAPICalls.js
  business-bridge-react/src/components/approval/item/ApprovalButton.js
  business-bridge-react/src/components/approval/item/Approver.js
  business-bridge-react/src/components/approval/item/BusinessDraftItem.js
  business-bridge-react/src/components/form/approvalForm/BDWriteForm.js
  business-bridge-react/src/components/form/approvalForm/ERWriteForm.js
  business-bridge-react/src/components/items/approvalItems/ApprovalButton.js
  business-bridge-react/src/components/items/approvalItems/ApprovalOpinionItem.js
  business-bridge-react/src/components/items/approvalItems/ApproverChoice.js
  business-bridge-react/src/components/items/approvalItems/ApproverView.js
  business-bridge-react/src/components/items/approvalItems/BusinessDraftItem.js
  business-bridge-react/src/components/items/approvalItems/ExpenseReportItem.js
  business-bridge-react/src/components/items/approvalItems/main/InProgressListItem.js
  business-bridge-react/src/components/items/approvalItems/main/InProgressLists.js
  business-bridge-react/src/components/modal/ApprovalFormModal.js
  business-bridge-react/src/components/modal/ApproverModal.js
  business-bridge-react/src/components/nav/ApprovalNavbar.js
  business-bridge-react/src/css/approval.css
  business-bridge-react/src/layouts/ApprovalLayout.js
  business-bridge-react/src/modules/ApprovalModule.js
  business-bridge-react/src/pages/approval/AppDetail.js
  business-bridge-react/src/pages/approval/AppWrite.js
  business-bridge-react/src/pages/businessbridge/approval/AppDetail.js
  business-bridge-react/src/pages/businessbridge/approval/AppMain.js
  business-bridge-react/src/pages/businessbridge/approval/ApproveApps.js
  business-bridge-react/src/pages/businessbridge/approval/ApproveAppsByStatus.js
  business-bridge-react/src/pages/businessbridge/approval/DraftApps.js
  business-bridge-react/src/pages/businessbridge/approval/DraftAppsByStatus.js
  business-bridge-react/src/pages/businessbridge/approval/DraftCollect.js
  business-bridge-react/src/pages/businessbridge/approval/ReceiveApps.js
  business-bridge-react/src/pages/businessbridge/approval/ReceiveAppsByStatus.js
  business-bridge-react/src/pages/businessbridge/approval/TempStorageApps.js
  business-bridge-react/src/pages/businessbridge/approval/UpcomingApps.js
  business-bridge-react/src/pages/businessbridge/approval/Write-BusinessDraft.js
  business-bridge-react/src/router/ProtectedRoute.js
Labels: 👩‍💻backend, 🎇feature

#41 Feature/#6/regist approval
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/ApprovalAPICalls.js
  business-bridge-react/src/components/form/approvalForm/BDWriteForm.js
  business-bridge-react/src/components/form/approvalForm/ERWriteForm.js
  business-bridge-react/src/components/items/approvalItems/ApprovalButton.js
  business-bridge-react/src/components/items/approvalItems/ApproverChoice.js
  business-bridge-react/src/components/items/approvalItems/ButtonForApprover.js
  business-bridge-react/src/components/items/approvalItems/ButtonForCollect.js
  business-bridge-react/src/components/items/approvalItems/ButtonForWriteBD.js
  business-bridge-react/src/components/items/approvalItems/ButtonForWriteER.js
  business-bridge-react/src/components/modal/ApproverModal.js
  business-bridge-react/src/css/approval.css
  business-bridge-react/src/modules/ApprovalModule.js
  business-bridge-react/src/pages/businessbridge/approval/AppDetail.js
  business-bridge-react/src/pages/businessbridge/approval/Write-BusinessDraft.js
  business-bridge-react/src/pages/businessbridge/approval/Write-ExpenseReport.js
Labels: 🖥frontend, 🎇feature

#43 Feat#40 account
  business-bridge-react/package-lock.json
  business-bridge-react/package.json
  business-bridge-react/src/App.js
  business-bridge-react/src/components/common/Header.js
  business-bridge-react/src/components/common/SalesNavbar.js
  business-bridge-react/src/components/modal/SalesProductModal.js
  business-bridge-react/src/components/modal/SalesRegistModal.js
  business-bridge-react/src/css/Sales.css
  business-bridge-react/src/modules/SalesModule.js
  business-bridge-react/src/pages/businessbridge/sales/SalesChart.js
  business-bridge-react/src/pages/businessbridge/sales/SalesDetail.js
  business-bridge-react/src/pages/businessbridge/sales/SalesList.js
  business-bridge-react/src/pages/businessbridge/sales/SalesModify.js
  business-bridge-react/src/pages/businessbridge/sales/SalesRegist.js
  business-bridge-react/src/pages/businessbridge/sales/SalesStatistics.js
Labels: 🖥frontend, 🎇feature

#50 Feat#40 account list
  business-bridge-react/public/images/sales-handshacke.png
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/AccountAPICalls.js
  business-bridge-react/src/apis/SalesAPICalls.js
  business-bridge-react/src/components/modal/AccountRegistModal.js
  business-bridge-react/src/components/modal/ProgressModal.js
  business-bridge-react/src/components/modal/SalesRegistModal.js
  business-bridge-react/src/components/nav/SalesNavbar.js
  business-bridge-react/src/css/Sales.css
  business-bridge-react/src/layouts/SalesLayout.js
  business-bridge-react/src/modules/AccountModule.js
  business-bridge-react/src/modules/index.js
  business-bridge-react/src/pages/businessbridge/account/AccountDetail.js
  business-bridge-react/src/pages/businessbridge/account/AccountList.js
  business-bridge-react/src/pages/businessbridge/account/AccountModify.js
  business-bridge-react/src/pages/businessbridge/account/AccountRegist.js
  business-bridge-react/src/pages/businessbridge/sales/SalesDetail.js
  business-bridge-react/src/pages/businessbridge/sales/SalesList.js
  business-bridge-react/src/pages/businessbridge/sales/SalesModify.js
Labels: 🖥frontend, 🎇feature

#56 Feat/#45/update app
  business-bridge-react/src/components/common/Header.js
  business-bridge-react/src/components/common/Menu.js
  business-bridge-react/src/components/form/approvalForm/BDUpdateForm.js
  business-bridge-react/src/components/items/approvalItems/ApprovalOpinionItem.js
  business-bridge-react/src/components/items/approvalItems/BusinessDraftItem.js
  business-bridge-react/src/components/items/approvalItems/ButtonForUpdateBD.js
  business-bridge-react/src/components/items/approvalItems/ButtonForUpdateER.js
  business-bridge-react/src/components/items/approvalItems/ButtonForWriteER.js
  business-bridge-react/src/components/items/approvalItems/main/InProgressListItem.js
  business-bridge-react/src/components/items/approvalItems/main/InProgressLists.js
  business-bridge-react/src/css/approval.css
  business-bridge-react/src/pages/businessbridge/Main.js
  business-bridge-react/src/pages/businessbridge/approval/AppDetail.js
  business-bridge-react/src/pages/businessbridge/approval/Write-BusinessDraft.js
  business-bridge-react/src/pages/businessbridge/approval/Write-ExpenseReport.js
Labels: 🖥frontend, 🎇feature

#59 Feat#40 account list
  .idea/workspace.xml
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/AccountAPICalls.js
  business-bridge-react/src/apis/SalesAPICalls.js
  business-bridge-react/src/components/items/approvalItems/main/InProgressLists.js
  business-bridge-react/src/components/main/Salesstatistics.js
  business-bridge-react/src/components/modal/AccountRegistModal.js
  business-bridge-react/src/components/modal/ProgressModal.js
  business-bridge-react/src/components/modal/SalesProductModal.js
  business-bridge-react/src/components/modal/SalesRegistModal.js
  business-bridge-react/src/components/nav/SalesNavbar.js
  business-bridge-react/src/css/Sales.css
  business-bridge-react/src/css/approval.css
  business-bridge-react/src/css/stylee.css
  business-bridge-react/src/pages/businessbridge/Main.js
  business-bridge-react/src/pages/businessbridge/approval/AppDetail.js
  business-bridge-react/src/pages/businessbridge/sales/SalesModify.js
  business-bridge-react/src/pages/businessbridge/sales/SalesStatistics.js
Labels: 🖥frontend, 🎇feature

#63 Feat/#26/product list
  business-bridge-react/src/App.js
  business-bridge-react/src/apis/ProductAPICalls.js
  business-bridge-react/src/components/common/Header.js
  business-bridge-react/src/components/items/ProductListItem.js
  business-bridge-react/src/components/lists/ProductList.js
  business-bridge-react/src/components/nav/ProductsNavbar.js
  business-bridge-react/src/css/Products.css
  business-bridge-react/src/css/stylee.css
  business-bridge-react/src/layouts/ProductsLayout.js
  business-bridge-react/src/modules/ProductModule.js
  business-bridge-react/src/modules/index.js
  business-bridge-react/src/pages/businessbridge/products/admin/ProductDetail.js
  business-bridge-react/src/pages/businessbridge/products/admin/ProductManagement.js
  business-bridge-react/src/pages/businessbridge/products/admin/ProductRegist.js
  business-bridge-react/src/pages/businessbridge/products/employee/CategoryMain.js
  business-bridge-react/src/pages/businessbridge/products/employee/ProductMain.js
Labels: 🖥frontend, 🎇feature
